### ISSUE TITLE
errore di inizializzazione

### ISSUE THREAD

**Issue by nonfederico** [nonfederico/ERBTelemetry#23]
la riga39 della classe Tab1 è la seguente:
	public DatePicker today = new DatePicker(LocalDate.now());

quando provo il test della classe Tab1 continua a darmi questo errore
relativo all'inizializzazione del DatePicker precedente:

java.lang.ExceptionInInitializerError
	at it.erb.telemetry/it.erb.telemetry.view.Tab1.<init>(Tab1.java:39)
	at it.erb.telemetry/it.erb.telemetry.view.Tab1Test.test(Tab1Test.java:20)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:436)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:431)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:724)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:686)
	at javafx.controls@20.0.2/javafx.scene.control.Control.<clinit>(Control.java:98)
	... 5 more

**Comment by SM-15** [comment]
Il problema è stato risolto nel branch add-test
